# alano config example

jobs:
  all:
    pre_jobs:
      - backup1
  backup1:
    command: restic
    env_vars: &pwd
      - RESTIC_PASSWORD: abc123
    flags:
      - --exclude: nwq*
      - --tag: job_backup1
      - -r: &repo d:\tmp\srv\repo1
    arguments:
      - backup
      - d:\tmp\n.txt
      - d:\tmp\man
    pre_jobs:
      - depjob1
    post_jobs:
      - forget1
  depjob1:
    command: restic
    env_vars: *pwd
    flags:
      - -r: *repo
    arguments:
      - snapshots
  forget1:
    command: restic
    env_vars: *pwd
    flags:
      - -r: *repo
      - --keep-last: 5
      # - --tag: job_backup1
    arguments:
      - forget
